title: RJâ€™s Bridge Logic
description: CRM/RevOps + Home Automation
theme: just-the-docs
url: https://rjsbridgelogic.org
baseurl: ""
search_enabled: true
aux_links:
  View on GitHub: https://github.com/ranjiet/portfolio
